export const firstColumns = [
  {
    title: "Mode",
    key: "mode",
    dataIndex: "mode",
    width: "200px",
    ellipsis: true,
  },
  {
    title: "Corner",
    key: "corner",
    dataIndex: "corner",
    width: "200px",
    ellipsis: true,
  },
  {
    title: "Path Group",
    key: "pathGroup",
    dataIndex: "pathGroup",
    width: "240px",
    ellipsis: true,
  },
  {
    title: "Analysis",
    key: "analysis",
    dataIndex: "analysis",
    width: "120px",
    ellipsis: true,
  },

  {
    title: () => <div style={{ textAlign: "left" }}>NVP</div>,
    key: "nvp",
    dataIndex: "nvp",
    width: "120px",
    ellipsis: true,
    align: "right",
  },
  {
    title: () => <div style={{ textAlign: "left" }}>WNS</div>,
    key: "wns",
    dataIndex: "wns",
    width: "120px",
    ellipsis: true,
    align: "right",
  },
  {
    title: () => <div style={{ textAlign: "left" }}>TNS</div>,
    key: "tns",
    dataIndex: "tns",
    width: "120px",
    ellipsis: true,
    align: "right",
  },
];

export const secondColumns = [
  {
    title: () => <div style={{ textAlign: "left" }}>slack</div>,
    key: "slack",
    dataIndex: "slack",
    width: "120px",
    ellipsis: true,
    sorter: (a: any, b: any) => a.slack - b.slack,
    sortDirection: ["descend", "ascend"],
    align: "right",
  },
  {
    title: "startpoint",
    key: "startPoint",
    dataIndex: "startPoint",
    ellipsis: true,
    width: "182px",
  },
  {
    title: "endpoint",
    key: "endPoint",
    dataIndex: "endPoint",
    ellipsis: true,
    width: "182px",
  },
  {
    title: "path_group",
    key: "pathGroup",
    dataIndex: "pathGroup",
    ellipsis: true,
    width: "90px",
  },
  {
    title: "startpoint_clock",
    key: "startpointClock",
    dataIndex: "startpointClock",
    ellipsis: true,
    width: "121px",
  },
  {
    title: "endpoint_clock",
    key: "endpointClock",
    dataIndex: "endpointClock",
    ellipsis: true,
    width: "141px",
  },
  {
    title: "path_type",
    key: "pathType",
    dataIndex: "pathType",
    ellipsis: true,
    width: "80px",
  },
  {
    title: () => <div style={{ textAlign: "left" }}>required</div>,
    key: "required",
    dataIndex: "required",
    ellipsis: true,
    width: "78px",
    align: "right",
  },
  {
    title: () => <div style={{ textAlign: "left" }}>arrival</div>,
    key: "arrival",
    dataIndex: "arrival",
    ellipsis: true,
    width: "64px",
    align: "right",
  },
  {
    title: "clock_uncertainty",
    key: "clock_uncertainty",
    dataIndex: "clock_uncertainty",
    ellipsis: true,
    width: "139px",
  },
];
